
/**
 * Name: Amit Bhandari
 * Student Id- 12080721
 * functionality:This class implement the IView interface which contains all the GUI stuffs.ALl the GUI created are 
drag and drop from the netbeans gui editor.

 */
package pis.view;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import pis.controller.SingleMaltController;
import pis.model.SingleMalt;
import pis.model.ViewState;

public class SingleMaltView extends javax.swing.JFrame implements IView, Observer {

    private final Observable singlemaltmodel;
    private final SingleMaltController controller;
    
//initializes the constructor
    public SingleMaltView(Observable smm, SingleMaltController smc) {
        this.singlemaltmodel = smm;
        this.controller = smc;
        initComponents();
        this.setTitle("Restaurant Booking System"); 
        nextBtn.setEnabled(false);
        previousBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ageRangeLabel = new javax.swing.JLabel();
        distilleryLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        regionLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        upperAgeRangeTxtField = new javax.swing.JTextField();
        distilleryTxtField = new javax.swing.JTextField();
        regionTxtField = new javax.swing.JTextField();
        ageTxtField = new javax.swing.JTextField();
        priceTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lowerAgeRangeTxtField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTxtArea = new javax.swing.JTextArea();
        queriesLabel = new javax.swing.JLabel();
        allMaltsBtn = new javax.swing.JButton();
        maltsFromRegionBtn = new javax.swing.JButton();
        maltsInAgeRangeBtn = new javax.swing.JButton();
        updatePriceBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ageRangeLabel.setText("Age Range");

        distilleryLabel.setText("Distillery");

        ageLabel.setText("Age");

        regionLabel.setText("Region");

        priceLabel.setText("Price");

        upperAgeRangeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperAgeRangeTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Input/Output");

        messageLabel.setText("Messages");

        messageTxtArea.setColumns(20);
        messageTxtArea.setRows(5);
        jScrollPane1.setViewportView(messageTxtArea);

        queriesLabel.setText("Queries");

        allMaltsBtn.setText("All Malts");
        allMaltsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMaltsBtnActionPerformed(evt);
            }
        });

        maltsFromRegionBtn.setText("Malts From Region");
        maltsFromRegionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltsFromRegionBtnActionPerformed(evt);
            }
        });

        maltsInAgeRangeBtn.setText("Malts in Age Range");
        maltsInAgeRangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltsInAgeRangeBtnActionPerformed(evt);
            }
        });

        updatePriceBtn.setText("Update Price ");
        updatePriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePriceBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(distilleryLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(distilleryTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(regionTxtField)
                            .addComponent(ageTxtField)
                            .addComponent(priceTxtField))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(ageRangeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(lowerAgeRangeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(upperAgeRangeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 24, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(allMaltsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(previousBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(updatePriceBtn))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceLabel)
                                    .addComponent(ageLabel)
                                    .addComponent(regionLabel)
                                    .addComponent(queriesLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maltsFromRegionBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maltsInAgeRangeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitBtn)))))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(messageLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(distilleryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(distilleryLabel))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(regionLabel)
                                    .addComponent(regionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageLabel)
                                    .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ageRangeLabel)
                                        .addComponent(lowerAgeRangeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(upperAgeRangeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(priceLabel)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(queriesLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allMaltsBtn)
                            .addComponent(updatePriceBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maltsFromRegionBtn)
                            .addComponent(clearBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maltsInAgeRangeBtn)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(exitBtn)
                                .addGap(36, 36, 36))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousBtn)
                            .addComponent(nextBtn))
                        .addGap(245, 245, 245))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upperAgeRangeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperAgeRangeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upperAgeRangeTxtFieldActionPerformed

     /**
     * Handles AllMalts Button Event 
     */
    private void allMaltsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMaltsBtnActionPerformed
        controller.allMalts();
    }//GEN-LAST:event_allMaltsBtnActionPerformed

    /**
     * Handles clear button event
     */
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        controller.clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * Handles Malts From Region button event
     */
    private void maltsFromRegionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltsFromRegionBtnActionPerformed
        String region = regionTxtField.getText();
        if (region.equals("")) {
            JOptionPane.showMessageDialog(null, "Error!! Please enter Region",
                    "Input Age Range", JOptionPane.ERROR_MESSAGE);
            return;
        }
        controller.maltsFromRegion(region);
    }//GEN-LAST:event_maltsFromRegionBtnActionPerformed

    /**
     * Handles Malts in Age Range Button Event 
     */
    private void maltsInAgeRangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltsInAgeRangeBtnActionPerformed
        String ageLowerRangeValue = lowerAgeRangeTxtField.getText();
        String ageUpperRangeValue = upperAgeRangeTxtField.getText();

        //checks whether user has entered data 
        if (ageLowerRangeValue.equals("") && ageUpperRangeValue.equals("")) {
            JOptionPane.showMessageDialog(null, "Error!! Please enter Age Range",
                    "Input Age Range", JOptionPane.ERROR_MESSAGE);
        } //checks whether lower age range value entered by user is numeric or not
        else if (!ageLowerRangeValue.equals("") && !isStringNumeric(ageLowerRangeValue)) {
            JOptionPane.showMessageDialog(null, "Error!!Lower(Left) Age limit should be numeric",
                    "Input Age Range", JOptionPane.ERROR_MESSAGE);
        } //checks whether upper age range value entered by user is numeric or not
        else if (!ageUpperRangeValue.equals("") && !isStringNumeric(ageUpperRangeValue)) {
            JOptionPane.showMessageDialog(null, "Error!!Upper(Right) Age Range must be numeric",
                    "Input Age Range", JOptionPane.ERROR_MESSAGE);
        } else {
            //sets lower limit age value of age to 0
            if (ageLowerRangeValue.equals("")) {
                ageLowerRangeValue = "0";
            }
            //sets upper limit value of age to 100
            if (ageUpperRangeValue.equals("")) {
                ageUpperRangeValue = "100";
            }

            int ageLowerRange = Integer.parseInt(ageLowerRangeValue); //convert String value of lower age to int
            int ageUpperRange = Integer.parseInt(ageUpperRangeValue); //convert String value of upper age to int

            //checks if upper bound of age is less than lower bound
            if (ageUpperRange < ageLowerRange) {
                JOptionPane.showMessageDialog(null, "Error!! Lower(Left) Age Range cannot be greater than Upper(Right) Age Range",
                        "Input Age Range", JOptionPane.ERROR_MESSAGE);
            } else {
                controller.maltsInAgeRange(ageLowerRangeValue, ageUpperRangeValue);
            }
        }
    }//GEN-LAST:event_maltsInAgeRangeBtnActionPerformed

    /**
     * Handles Update Price button event
     */
    private void updatePriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePriceBtnActionPerformed
        String distilleryValue = distilleryTxtField.getText(); //get Distillery from user
        String ageValue = ageTxtField.getText(); //get Age from user
        String priceValue = priceTxtField.getText(); //get Price from user

        //checks whether user has entered  data or not
        if (distilleryValue.equals("") || ageValue.equals("") || priceValue.equals("")) {
            JOptionPane.showMessageDialog(null, "Error!!Distillery, Age and Price value is required inorder to Update price",
                    "Input to Update Price", JOptionPane.ERROR_MESSAGE);
        } //checks whether user has entered numeric value for Age or not
        else if (!isStringNumeric(ageValue)) {
            JOptionPane.showMessageDialog(null, "Error!! Please enter numeric value for Age",
                    "Input to Update Price", JOptionPane.ERROR_MESSAGE);
        } //checks whether user has entered numeric value for Price or not
        else if (!isStringNumeric(priceValue)) {
            JOptionPane.showMessageDialog(null, "Error!!Please enter numeric value for Price",
                    "Input to Update Price", JOptionPane.ERROR_MESSAGE);
        } else {
            controller.updatePrice(distilleryValue, ageValue, priceValue);
        }
    }//GEN-LAST:event_updatePriceBtnActionPerformed

    /**
     *  method Handles Exit button event
     */
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed

        controller.closeConnection();//close connection
        
        System.exit(0);//close application
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * method Handles Previous button event 
     */
    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        controller.previous();
    }//GEN-LAST:event_previousBtnActionPerformed

    /**
     * method Handles Next button event
     */
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        controller.next();
    }//GEN-LAST:event_nextBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageRangeLabel;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton allMaltsBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel distilleryLabel;
    private javax.swing.JTextField distilleryTxtField;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lowerAgeRangeTxtField;
    private javax.swing.JButton maltsFromRegionBtn;
    private javax.swing.JButton maltsInAgeRangeBtn;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTxtArea;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton previousBtn;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JLabel queriesLabel;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JTextField regionTxtField;
    private javax.swing.JButton updatePriceBtn;
    private javax.swing.JTextField upperAgeRangeTxtField;
    // End of variables declaration//GEN-END:variables

    
    // Method that display message in text Area
    @Override
    public void display(String s) {
        messageTxtArea.setText(s);
    }

    //method enables or disables browsing option i.e next and previous button
    @Override
    public void browsing(boolean on) {
        nextBtn.setEnabled(on);
        previousBtn.setEnabled(on);
    }
//method updates the field in the text area and text field
    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof String) {
            browsing(false);
            messageTxtArea.setText(arg.toString());
            distilleryTxtField.setText("");
            ageTxtField.setText("");
            regionTxtField.setText("");
            priceTxtField.setText("");
            upperAgeRangeTxtField.setText("");
            lowerAgeRangeTxtField.setText("");
        }
        if (arg instanceof ViewState) {
            browsing(true);
            ViewState viewState = (ViewState) arg;
            SingleMalt singleMalt = viewState.getSingleMalt();
            distilleryTxtField.setText(singleMalt.getDistillery());
            ageTxtField.setText(String.valueOf(singleMalt.getAge()));
            regionTxtField.setText(singleMalt.getRegion());
            priceTxtField.setText(String.valueOf(singleMalt.getPrice()));
            messageTxtArea.setText(viewState.getMessageDisplay());

        }
    }

   
    // Method that checks whether the string entered by user is an alphabet or numeric value
    
    private boolean isStringNumeric(String str) {
        for (int i = 0; i < str.length(); i++) {
            if (!Character.isDigit(str.charAt(i))) {
                return false;
            }
        }

        return true;
    }
}
